name: Standard

description: |
  This composite GitHub Action runs Brakeman on the codebase.

outputs:
  success:
    description: 'Whether the Brakeman check passed'
    value: ${{ steps.status.outputs.results }}

runs:
  using: "composite"
  steps:
    - name: Run Brakeman
      shell: bash
      run: bin/brakeman -AI

    - name: Output Status
      if: ${{ always() }}
      id: status
      shell: bash
      run: |
        echo "::set-output name=results::Brakeman ${{ (job.status == 'success' && '✅') || '❌' }}"
        echo "- Brakeman : ${{ (job.status == 'success' && '✅') || '❌' }}" >> $GITHUB_STEP_SUMMARY
      # run: echo "results=$(echo $?)" >> $GITHUB_OUTPUT
