name: Standard

description: |
  This composite GitHub Action runs Brakeman on the codebase.

outputs:
  success:
    description: 'Whether the Brakeman check passed'
    value: ${{ steps.status.outputs.results }}

runs:
  using: "composite"
  steps:
    - name: Run Brakeman
      shell: bash
      run: bin/brakeman --format github --quiet --run-all-checks

    - name: Output Status
      if: ${{ always() }}
      id: status
      shell: bash
      run: |
        echo "results=${{ (job.status == 'success' && '✅') || '❌' }}" >> $GITHUB_OUTPUT
