name: Standard

description: |
  This composite GitHub Action checks out the repository and runs
  the StandardRB linter.

outputs:
  success:
    description: 'Whether the StandardRB check passed'
    value: ${{ steps.status.outputs.results }}

runs:
  using: "composite"
  steps:
    - name: Run StandardRB
      shell: bash
      run: bin/standardrb

    - name: Output Status
      if: always()
      id: status
      shell: bash
      run: |
        echo "results=${ (job.status == 'success' && '✅') || '❌' }" >> $GITHUB_OUTPUT
      # echo "- Standard : ${{ (job.status == 'success' && '✅') || '❌' }}" >> $GITHUB_STEP_SUMMARY
