name: "CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    name: Build Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-ruby
      - uses: ./.github/actions/setup-node

  lint:
    name: Lint
    needs: build
    uses: ./.github/workflows/lint.yml

  test:
    name: Test
    needs: build
    uses: ./.github/workflows/test.yml
