name: "CI"

on:
  pull_request:
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  setup_ruby:
    name: Setup Ruby Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-ruby

  setup_node:
    name: Setup Node Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node

  lint:
    name: Lint
    needs:
      - setup-ruby
    uses: ./.github/workflows/lint.yml

  test:
    name: Test
    needs:
      - setup_ruby
      - setup_node
    uses: ./.github/workflows/test.yml
