name: "Lint"

on:
  workflow_call:

jobs:
  standard:
    name: Standardrb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-ruby
      - uses: ./.github/actions/standard

  brakeman:
    name: Brakeman
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-ruby
      - uses: ./.github/actions/brakeman
