name: "Lint"

on:
  workflow_call:

jobs:
  standard:
    name: Standardrb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-ruby
      - uses: ./.github/actions/standard
        id: standardrb

      - name: Print check result
        run: echo '✅ StandardRB:\ ${{ steps.standardrb.outputs.success }}' >> $GITHUB_STEP_SUMMARY

  brakeman:
    name: Brakeman
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-ruby
      - uses: ./.github/actions/brakeman
        id: brakeman

      - name: Print check result
        run: echo '✅ Brakeman:\ ${{ steps.brakeman.outputs.success }}' >> $GITHUB_STEP_SUMMARY
