name: "Lint"

on:
  workflow_call:

jobs:
  standard:
    name: Standardrb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-ruby

      - name: Run StandardRB
        id: standardrb
        uses: ./.github/actions/standard

      - name: Print StandardRB check result
        run: echo '✅ StandardRB:\ ${{ steps.standardrb.outputs.success }}' >> $GITHUB_STEP_SUMMARY
        continue-on-error: true

  brakeman:
    name: Brakeman
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-ruby
      - uses: ./.github/actions/brakeman
