name: "Lint"

on:
  workflow_call:

jobs:
  standard:
    name: Standardrb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-ruby
      - uses: ./.github/actions/standard
        id: standardrb

  brakeman:
    name: Brakeman
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-ruby
      - uses: ./.github/actions/brakeman
        id: brakeman

  combine-results:
    name: Combine results
    needs: [standard, brakeman]
    runs-on: ubuntu-latest
    steps:
      - name: Combine results
        if: always()
        run: |
          echo '✅ StandardRB:\ ${{ needs.standard.outputs.success }}' >> $GITHUB_STEP_SUMMARY
          echo '✅ Brakeman:\ ${{ needs.brakeman.outputs.success }}' >> $GITHUB_STEP_SUMMARY
