name: "Lint"

on:
  workflow_call:

jobs:
  standardrb:
    name: Standardrb
    runs-on: ubuntu-latest
    outputs:
      results: ${{ steps.standardrb.outputs.status }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-ruby
      - uses: ./.github/actions/standard
        id: standardrb


  brakeman:
    name: Brakeman
    runs-on: ubuntu-latest
    outputs:
      results: ${{ steps.brakeman.outputs.status }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-ruby
      - uses: ./.github/actions/brakeman
        id: brakeman

  combine-results:
    name: Combine results
    needs: [standardrb, brakeman]
    runs-on: ubuntu-latest
    if: ${{ always() }}

    steps:
      - name: Combine results
        run: |
          echo 'StandardRB: ${{ needs.standardrb.outputs.results }}' >> $GITHUB_STEP_SUMMARY
          echo 'Brakeman: ${{ needs.brakeman.outputs.results }}' >> $GITHUB_STEP_SUMMARY
