name: Test

on:
  workflow_call:

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://actions:password@localhost:5432/actions_test"
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: actions_test
          POSTGRES_USER: actions
          POSTGRES_PASSWORD: password
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-ruby
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/setup-db
      - uses: ./.github/actions/precompile-assets
      - run: bin/test
      - if: success()
        run: echo '✅ Unit Tests ' >> $GITHUB_STEP_SUMMARY
      - if: failure()
        run: echo '❌ Unit Tests ' >> $GITHUB_STEP_SUMMARY
  system_test:
    name: System Tests
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://actions:password@localhost:5432/actions_test"
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: actions_test
          POSTGRES_USER: actions
          POSTGRES_PASSWORD: password
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-ruby
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/setup-db
      - uses: ./.github/actions/precompile-assets
      - run: bin/system_test
      - if: success()
        run: echo '✅ Unit Tests ' >> $GITHUB_STEP_SUMMARY
      - if: failure()
        run: echo '❌ Unit Tests ' >> $GITHUB_STEP_SUMMARY
