name: Test

on:
  workflow_call:
    # inputs:
    #   enable-code-scans:
    #     required: false
    #     type: boolean
    # secrets:
    #   ghcr-token:
    #     required: true
    #     description: Github token allowing access to the libraries and ghcr.

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://actions:password@localhost:5432/actions_test"
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: actions_test
          POSTGRES_USER: actions
          POSTGRES_PASSWORD: password
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-ruby
      - uses: ./.github/actions/setup-node

      - name: Setup test database
        run: bin/rails db:schema:load

      - name: Precompile Assets
        run: bin/rails assets:precompile

      - name: Run tests
        run: bin/rspec

      - name: Adding markdown
        run: echo '### Hello world! ' >> $GITHUB_STEP_SUMMARY
